### ISSUE TITLE
Not able to see React warning/errors

### ISSUE THREAD

**Issue by naminder-trantor** [philnash/react-express-starter#10]
Hi,

Thanks for the solution. Everything works fine.

Just wanted to confirm if there is a way to keep printing the logs or console of create-react-app.

Thanks.

**Comment by philnash** [comment]
The logs may be being hidden because the two start scripts are being run in parallel.

A quick fix would be to run `npm start` in one terminal tab and `npm run server` in another to keep them separate.

Let me know if that helps.

**Comment by naminder-trantor** [comment]
Thanks Phil, I am already doing that, I already had 2 applications running in parallel.

I was trying to merge and so they can start with one command.

With your code I am able to achieve that, the only challenge now I see is, I cannot show logs of create-react-app.

Thanks.
